name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install, build and test"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}_dist-${{ github.run_id }}
          path: |
            dist
            !dist/**/*.md
          retention-days: 3
